"""
Business Document Content Generator Module.

This module implements the content creation tools registered in the executor's
Tool Registry.

The generator uses the application's standardized LLM client to:
1. Generate a document outline.
2. Generate detailed sections sequentially.
3. Compile the sections into a complete professional Markdown document.

Design Decisions:
1. Tool-Based Design:
   Every handler follows the (ExecutorState, Task) interface expected by the
   Executor Tool Registry.

2. Section-Based Generation:
   Large documents are generated section-by-section instead of asking the LLM
   to produce the entire document in a single response.

3. Contextual Writing:
   Previously generated sections are supplied selectively to later sections
   to maintain consistency without repeatedly sending the entire document.

4. Content Preservation:
   The refinement stage is instructed to preserve substantive content rather
   than aggressively summarize the generated sections.

5. Assumption Handling:
   Missing information is handled through explicit assumptions stored in the
   executor state.
"""

from llm import GeminiClient
from models import ExecutorState, Task
from prompts import (
    OUTLINE_SYSTEM_PROMPT,
    REFINER_SYSTEM_PROMPT,
    SECTION_GENERATOR_SYSTEM_PROMPT,
)
from utils import ExecutorException, logger


class DocumentGenerator:
    """
    Generates structured business-document content.

    The methods in this class are registered as tools in the Executor and are
    invoked according to the plan generated by the Planner.
    """

    def __init__(self, client: GeminiClient | None = None) -> None:
        """
        Initialize the document generator.

        Args:
            client: Optional standardized LLM client. If omitted, the default
                    application LLM client is created.
        """
        self.client = client or GeminiClient()

    # ------------------------------------------------------------------
    # OUTLINE GENERATION
    # ------------------------------------------------------------------

    def generate_outline(self, state: ExecutorState, task: Task) -> str:
        """
        Generate the hierarchical outline for the document.

        The outline determines the structure that subsequent section-generation
        tasks will follow.
        """
        logger.info(
            "Executing tool 'generate_outline' for document type: "
            f"{state.document_type}"
        )

        assumptions_str = (
            "\n".join(f"- {a}" for a in state.assumptions)
            if state.assumptions
            else "None"
        )

        prompt = OUTLINE_SYSTEM_PROMPT.format(
            document_type=state.document_type,
            request=state.original_request,
            assumptions=assumptions_str,
        )

        outline = self.client.generate(
            prompt=prompt,
            response_format="text",
        )

        if not outline or not outline.strip():
            raise ExecutorException(
                "The LLM returned an empty document outline."
            )

        logger.info(
            f"Document outline generated successfully "
            f"({len(outline)} characters)."
        )

        return outline.strip()

    # ------------------------------------------------------------------
    # SECTION GENERATION
    # ------------------------------------------------------------------

    def generate_section(self, state: ExecutorState, task: Task) -> str:
        """
        Generate detailed content for one document section.

        The method retrieves:
        - the generated outline
        - relevant previous sections
        - known assumptions
        - the original request

        This gives the LLM enough context to maintain consistency while
        preventing unnecessary context growth.
        """

        logger.info(
            f"Executing tool 'generate_section' for: "
            f"'{task.description}'"
        )

        # --------------------------------------------------------------
        # Retrieve generated outline
        # --------------------------------------------------------------

        outline = ""

        for completed_task in state.tasks:
            if (
                completed_task.action == "generate_outline"
                and completed_task.status == "completed"
                and completed_task.output
            ):
                outline = completed_task.output
                break

        if not outline:
            logger.warning(
                "Outline not found in state history. "
                "Generating section without outline context."
            )

        # --------------------------------------------------------------
        # Retrieve previous sections
        # --------------------------------------------------------------

        previous_sections: list[str] = []

        for completed_task in state.tasks:
            if (
                completed_task.action == "generate_section"
                and completed_task.status == "completed"
                and completed_task.output
            ):
                previous_sections.append(
                    f"SECTION: {completed_task.description}\n"
                    f"{completed_task.output}"
                )

        # Use the two most recent sections for continuity.
        #
        # We intentionally avoid sending the complete document every time,
        # because doing so unnecessarily increases token usage.
        previous_content_str = "\n\n".join(previous_sections[-2:])

        if not previous_content_str:
            previous_content_str = (
                "No previous sections have been generated yet."
            )

        # Keep context bounded, but substantially larger than the old
        # 800-character limit.
        max_previous_context_chars = 12000

        if len(previous_content_str) > max_previous_context_chars:
            previous_content_str = (
                previous_content_str[-max_previous_context_chars:]
            )

        # --------------------------------------------------------------
        # Format assumptions
        # --------------------------------------------------------------

        assumptions_str = (
            "\n".join(f"- {a}" for a in state.assumptions)
            if state.assumptions
            else "None"
        )

        # --------------------------------------------------------------
        # Build detailed section-generation prompt
        # --------------------------------------------------------------

        prompt = f"""
You are a professional business document writer.

Your responsibility is to write ONE COMPLETE SECTION of a larger
professional business document.

DOCUMENT TYPE:
{state.document_type}

ORIGINAL USER REQUEST:
{state.original_request}

DOCUMENT OUTLINE:
{outline}

KNOWN ASSUMPTIONS:
{assumptions_str}

PREVIOUS SECTIONS:
{previous_content_str}

CURRENT SECTION:
{task.description}

============================================================
WRITING REQUIREMENTS
============================================================

Write the complete substantive content for the current section.

This is NOT a short-answer task.

The document will be delivered to a professional audience, so the
section must contain useful, specific and well-organized information.

Target approximately 250-450 words for a normal section.

For sections such as:
- Budget
- Timeline
- Implementation Plan
- Risks
- Competitive Analysis
- Requirements

use tables, bullet lists, numbered lists, or structured subsections
when they improve clarity.

============================================================
CONTENT QUALITY
============================================================

1. Directly address the original user request.

2. Provide substantive content rather than generic statements.

3. Use the constraints from the request consistently.

4. When information is missing, make reasonable assumptions.

5. Clearly distinguish assumptions from facts.

6. Do not invent verified statistics, market figures, customer numbers,
   or external facts.

7. Do not use placeholders such as:
   [TBD]
   [Insert here]
   [Add information]
   [Company Name]

8. If a value must be estimated, explicitly label it as an estimate
   or assumption.

9. Maintain consistency with previously generated sections.

10. Avoid repeating entire paragraphs from previous sections.

11. Do not omit important details merely to keep the response short.

============================================================
DOCUMENT STYLE
============================================================

Use professional business language.

Prefer:

- clear paragraphs
- concise but meaningful explanations
- bullet lists
- numbered steps
- Markdown tables where appropriate
- clear subsections

Do not use:

- emojis
- conversational filler
- "As an AI..."
- explanations about your generation process
- meta-commentary

============================================================
OUTPUT FORMAT
============================================================

Return ONLY the content for the current section.

Do not provide an introduction such as:
"Here is the section..."

Do not provide a conclusion unless it naturally belongs to this
specific section.

Do not generate other sections.
"""

        # --------------------------------------------------------------
        # Generate section
        # --------------------------------------------------------------

        section_content = self.client.generate(
            prompt=prompt,
            response_format="text",
        )

        if not section_content or not section_content.strip():
            raise ExecutorException(
                f"LLM returned empty content for section "
                f"'{task.description}'."
            )

        section_content = section_content.strip()

        logger.info(
            f"Completed writing section: '{task.description}' "
            f"({len(section_content)} characters)."
        )

        return section_content

    # ------------------------------------------------------------------
    # FINAL REFINEMENT
    # ------------------------------------------------------------------

    def refine_content(self, state: ExecutorState, task: Task) -> str:
        """
        Compile all generated sections into a polished Markdown document.

        The refiner improves consistency and formatting while preserving the
        substantive content generated by earlier tasks.

        IMPORTANT:
        The refiner must not turn a multi-page document into a short summary.
        """

        logger.info(
            "Executing tool 'refine_content' to compile "
            "all draft sections."
        )

        # --------------------------------------------------------------
        # Collect generated sections
        # --------------------------------------------------------------

        sections_to_compile: list[str] = []

        for completed_task in state.tasks:
            if (
                completed_task.action == "generate_section"
                and completed_task.status == "completed"
                and completed_task.output
            ):
                sections_to_compile.append(
                    f"## {completed_task.description}\n\n"
                    f"{completed_task.output}"
                )

        if not sections_to_compile:
            raise ExecutorException(
                "Cannot execute refiner: no draft sections found "
                "in state history."
            )

        draft_sections_str = "\n\n".join(sections_to_compile)

        # --------------------------------------------------------------
        # Format assumptions
        # --------------------------------------------------------------

        assumptions_str = (
            "\n".join(f"- {a}" for a in state.assumptions)
            if state.assumptions
            else "None"
        )

        # --------------------------------------------------------------
        # Detailed refinement prompt
        # --------------------------------------------------------------

        prompt = f"""
You are the final editor for a professional business document.

DOCUMENT TYPE:
{state.document_type}

ORIGINAL USER REQUEST:
{state.original_request}

KNOWN ASSUMPTIONS:
{assumptions_str}

============================================================
DRAFT SECTIONS
============================================================

{draft_sections_str}

============================================================
YOUR TASK
============================================================

Produce the FINAL Markdown document.

Your primary objective is to improve the quality and coherence of the
document WITHOUT significantly reducing its substantive content.

============================================================
CRITICAL CONTENT-PRESERVATION RULE
============================================================

DO NOT summarize the draft.

DO NOT turn detailed sections into short paragraphs.

DO NOT remove useful details simply because multiple sections discuss
related topics.

DO NOT significantly reduce the document length.

Preserve:

- important requirements
- constraints
- numbers
- budget amounts
- timeline details
- implementation details
- risks
- mitigations
- assumptions
- technical considerations
- business considerations
- recommendations
- decision criteria

============================================================
YOU MAY IMPROVE
============================================================

- grammar
- spelling
- sentence structure
- heading hierarchy
- transitions
- formatting
- consistency
- genuinely duplicated sentences
- table formatting
- list organization
- terminology consistency

============================================================
DOCUMENT REQUIREMENTS
============================================================

The final document must:

1. Directly answer the original request.

2. Contain every major section generated in the draft.

3. Preserve the substantive information from every section.

4. Maintain consistency between:
   - budget
   - scope
   - timeline
   - team
   - implementation plan

5. Clearly identify assumptions.

6. Remove all placeholders.

7. Avoid unsupported claims.

8. Use professional business language.

9. Be suitable for presentation to a client, manager, executive,
   investor, or other professional audience.

10. Normally contain at least 1800 words for a business proposal or
    similarly substantial document.

If the source material contains enough information, the final document
should normally be 1800-3000 words.

Do not artificially add meaningless text just to reach the word count.

============================================================
MARKDOWN FORMAT
============================================================

Use:

# Document Title

## Major Section

### Subsection

Use Markdown tables where useful.

Use bullet lists for grouped information.

Use numbered lists for ordered procedures or implementation phases.

Do not put the entire document inside a code block.

============================================================
OUTPUT
============================================================

Return ONLY the final Markdown document.

Do not explain your editing process.
Do not say "Here is the final document".
"""

        refined_document = self.client.generate(
            prompt=prompt,
            response_format="text",
        )

        if not refined_document or not refined_document.strip():
            raise ExecutorException(
                "LLM returned an empty refined document."
            )

        refined_document = refined_document.strip()

        logger.info(
            "Document refinement and compilation complete "
            f"({len(refined_document)} characters)."
        )

        # Useful diagnostic information for the demo/logs.
        word_count = len(refined_document.split())

        logger.info(
            f"Final refined document size: approximately "
            f"{word_count} words."
        )

        return refined_document