"""
Executor Module for the Autonomous Business Document Agent.

The Executor executes the plan generated by the Planner using a dynamic
Tool Registry.

Architecture:

    Planner
       ↓
    Task[]
       ↓
    Executor
       ↓
    Tool Registry
       ↓
    DocumentGenerator
       ↓
    Task Outputs
       ↓
    Final Refined Document
"""


from typing import Callable, Dict

from document_generator import DocumentGenerator
from models import ExecutorState, Task
from utils import ExecutorException, logger


class Executor:
    """
    Executes planned document-generation tasks sequentially.

    A Tool Registry maps planner actions to executable handlers.
    """

    def __init__(
        self,
        doc_generator: DocumentGenerator | None = None,
    ) -> None:

        self.generator = (
            doc_generator
            or DocumentGenerator()
        )

        self.tools: Dict[
            str,
            Callable[[ExecutorState, Task], str],
        ] = {
            "generate_outline":
                self.generator.generate_outline,

            "generate_section":
                self.generator.generate_section,

            "refine_content":
                self.generator.refine_content,
        }

    def execute(
        self,
        state: ExecutorState,
    ) -> ExecutorState:
        """
        Execute every planned task sequentially.
        """

        logger.info(
            "Beginning sequential execution of "
            f"{len(state.tasks)} plan tasks."
        )

        for index, task in enumerate(
            state.tasks,
            start=1,
        ):

            if task.status == "completed":

                logger.info(
                    f"Task {index}/{len(state.tasks)} already completed. "
                    "Skipping."
                )

                continue

            logger.info(
                f"Task {index}/{len(state.tasks)}: "
                f"Starting '{task.description}' "
                f"[Action: {task.action}]"
            )

            task.status = "running"

            state.logs.append(
                f"Task {index}/{len(state.tasks)}: "
                f"Started '{task.description}' "
                f"({task.action})"
            )

            try:

                # ------------------------------------------------------
                # Validate tool
                # ------------------------------------------------------

                if task.action not in self.tools:

                    raise ExecutorException(
                        f"Unregistered action "
                        f"'{task.action}' requested by planner."
                    )

                handler = self.tools[
                    task.action
                ]

                # ------------------------------------------------------
                # Execute tool
                # ------------------------------------------------------

                output_content = handler(
                    state,
                    task,
                )

                if output_content is None:
                    output_content = ""

                output_content = str(
                    output_content
                ).strip()

                # ------------------------------------------------------
                # Store output
                # ------------------------------------------------------

                task.output = output_content

                task.status = "completed"

                # ------------------------------------------------------
                # Diagnostics
                # ------------------------------------------------------

                logger.info(
                    f"Task {index}/{len(state.tasks)} completed: "
                    f"{len(output_content)} characters generated."
                )

                if task.action == "generate_section":

                    logger.info(
                        f"SECTION OUTPUT [{index}]: "
                        f"{task.description}"
                    )

                    logger.info(
                        f"SECTION LENGTH: "
                        f"{len(output_content)} chars / "
                        f"{len(output_content.split())} words"
                    )

                # ------------------------------------------------------
                # Final aggregation
                # ------------------------------------------------------

                if task.action == "refine_content":

                    state.document_content = (
                        output_content
                    )

                    logger.info(
                        "FINAL REFINED DOCUMENT LENGTH: "
                        f"{len(state.document_content)} characters"
                    )

                    logger.info(
                        "FINAL REFINED DOCUMENT WORD COUNT: "
                        f"{len(state.document_content.split())}"
                    )

                log_success = (
                    f"Task {index}/{len(state.tasks)}: "
                    "Completed successfully."
                )

                logger.info(log_success)

                state.logs.append(
                    log_success
                )

            except Exception as e:

                task.status = "failed"

                log_error = (
                    f"Task {index}/{len(state.tasks)}: "
                    f"Failed with error: {e}"
                )

                logger.error(log_error)

                state.logs.append(
                    log_error
                )

                raise ExecutorException(
                    f"Failed executing task "
                    f"'{task.description}': {e}",
                    details=str(e),
                ) from e

        # --------------------------------------------------------------
        # Final diagnostic
        # --------------------------------------------------------------

        section_tasks = [
            task
            for task in state.tasks
            if task.action == "generate_section"
            and task.output
        ]

        logger.info(
            "Execution complete. Generated "
            f"{len(section_tasks)} document sections."
        )

        for task in section_tasks:

            logger.info(
                f"Retained section: "
                f"'{task.description}' "
                f"({len(task.output or '')} chars)"
            )

        logger.info(
            "Document compilation tasks successfully completed."
        )

        return state