"""
Pydantic Models for the Autonomous Business Document Agent.

This module defines all Pydantic schemas used for API validation, structured tool schemas
for LLM interaction, executor state tracking, and reflection result schemas.

Design Decisions:
1. Strict Validation: Request strings are checked to ensure they are not blank or trivially short,
   failing fast at the API gateway layer.
2. Structured Planning: Tasks are structured with an 'action' key matching the Tool Registry.
   This prevents arbitrary planner outputs and aligns the planner directly with executable modules.
3. Separation of Concerns: Separate models are defined for API input, Planner output,
   Reflection output, and the final Response, ensuring clean data boundaries.
"""

from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class AgentRequest(BaseModel):
    """
    Schema for validating incoming natural language document generation requests.
    """

    request: str = Field(
        ...,
        description="The natural language query describing the business document to generate.",
        examples=[
            "Create a project proposal for implementing an AI chatbot in a hospital."
        ],
    )

    @field_validator("request")
    @classmethod
    def validate_request(cls, v: str) -> str:
        """
        Ensures the request string contains meaningful text.
        """
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("The request string cannot be empty or whitespace-only.")
        if len(cleaned) < 10:
            raise ValueError(
                "The request is too short (minimum 10 characters). "
                "Please describe the document you want to generate in more detail."
            )
        return cleaned


class Task(BaseModel):
    """
    Represents an individual unit of work in the agent's execution checklist.
    """

    action: str = Field(
        ...,
        description="The registry tool key to execute (e.g. 'generate_outline', 'generate_content').",
    )
    description: str = Field(
        ...,
        description="A human-readable description of what this task accomplishes.",
    )
    status: str = Field(
        default="pending",
        description="The current run status of the task ('pending', 'running', 'completed', 'failed').",
    )
    output: Optional[str] = Field(
        default=None,
        description="Intermediate result or section content produced by this task.",
    )


class PlannerPlan(BaseModel):
    """
    The structured plan generated by the Planner Agent.
    """

    document_type: str = Field(
        ...,
        description="The inferred business document category (e.g., 'Project Proposal', 'Technical Design').",
    )
    tasks: List[Task] = Field(
        ...,
        description="An ordered list of structured tasks required to fulfill the request.",
    )
    assumptions: List[str] = Field(
        default_factory=list,
        description="Reasonable assumptions made by the planner based on missing details in the request.",
    )


class ExecutorState(BaseModel):
    """
    Maintains the state across task executions. Used by the Executor.
    """

    original_request: str = Field(
        ..., description="The original request input from the user."
    )
    document_type: str = Field(
        ..., description="The inferred type of document being created."
    )
    tasks: List[Task] = Field(
        ..., description="The current checklist of tasks with their execution states."
    )
    assumptions: List[str] = Field(
        default_factory=list,
        description="The running list of assumptions made throughout the project.",
    )
    document_content: str = Field(
        default="",
        description="Accumulated draft document text (markdown or formatted plain text).",
    )
    logs: List[str] = Field(
        default_factory=list,
        description="Detailed execution steps and explanation logs for transparency.",
    )


class ReflectionOutput(BaseModel):
    """
    Structured output returned by the Reflection Module.
    """

    approved: bool = Field(
        ...,
        description="True if the content passes quality checks. False if revisions are needed.",
    )
    feedback: str = Field(
        ...,
        description="Detailed review comments focusing on grammar, tone, flow, structure, and missing details.",
    )
    improved_content: Optional[str] = Field(
        default=None,
        description="The complete rewritten text if revisions were made. None if approved is True.",
    )


class AgentResponse(BaseModel):
    """
    The structured response sent back to the API client.
    """

    status: str = Field(
        ...,
        description="Indicates execution status, typically 'success' or 'error'.",
    )
    tasks: List[str] = Field(
        ...,
        description="The human-readable description of all executed tasks.",
    )
    assumptions: List[str] = Field(
        ...,
        description="List of all assumptions formulated during the generation process.",
    )
    document_type: str = Field(
        ...,
        description="The category of business document generated.",
    )
    generated_file: str = Field(
        ...,
        description="Relative file path of the generated MS Word document (.docx).",
    )
    preview: str = Field(
        ...,
        description="A short plain text snippet/preview of the final document.",
    )
    execution_summary: str = Field(
        ...,
        description="A detailed summary outlining the agent's work, reflection cycles, and execution metrics.",
    )
